FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt install -y nodejs && rm -rf /var/lib/apt/lists/*
WORKDIR /app/src
COPY src/ .
RUN dotnet restore NoaaWeb.App/NoaaWeb.App.csproj
RUN dotnet publish -c Release NoaaWeb.App/NoaaWeb.App.csproj -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/build/ ./
ENTRYPOINT ["dotnet", "NoaaWeb.App.dll"]